services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: lucas
    ports:
      - 5432:5432

  webapi:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:

