version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: lucas

    # if "docker run" expose 5432:5423 for testing purpose
