version: '3.9'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: lucas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lucasapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:

